### ISSUE TITLE
bmc fw update: use `bmc_fw_update_job_wait` argument to add `when` statement in the task

### ISSUE THREAD

**Issue by glimchb** [opiproject/ansible-opi-dpu#21]
from #2 add when statement to:

```
- name: Get the status of an update operation in a loop
  community.general.redfish_info:
    category: Update
    command: GetUpdateStatus
    baseuri: "{{ inventory_hostname }}"
    username: "{{ dpu_bmc_username }}"
    password: "{{ dpu_bmc_password }}"
    update_handle: "{{ result_update_task.return_values.update_status.handle }}"
  register: update_progress
  until: update_progress.redfish_facts.update_status.status != 'Running'
  retries: 60
  delay: 30
  delegate_to: localhost
  ```
