### ISSUE TITLE
user/pass/token: make task names and block names match

### ISSUE THREAD

**Issue by glimchb** [opiproject/ansible-opi-dpu#70]
reported by @jcastanos2 on #67 

for example:
```
- name: Reboot BMC when username and password are defined
  when: dpu_bmc_username is defined and dpu_bmc_password is defined
  block:
    - name: Reboot BMC to apply new firmware of DPU
      community.general.redfish_command:
```
and
```
- name: Reboot BMC when auth_token is defined
  when: dpu_bmc_token is defined
  block:
    - name: Reboot BMC to apply new firmware of DPU
      community.general.redfish_command:
```

the block name distinguishes between user/pass and token
but following task name doesn't

from the run log it is not clear which method was used inside the role...

please align...
